### ISSUE TITLE
Template variable : multi-selecting host gives : "Error message: Bad Request These fields have problems: host_name"

### ISSUE THREAD

**Issue by fabriceverkor** [Checkmk/grafana-checkmk-datasource#248]
I have the following installation :
CMK version: 2.2.0p14 raw
OS version: Debian Bulleyes
CheckMK plugin: tribe-29-checkmk-datasource @ 3.2.2
Grafana version: v10.4.2

I followed [Integrating Checkmk in Grafana 1](https://docs.checkmk.com/latest/en/grafana.html) to use variables.
The menu allowing to multi-select hosts is present.
If a select one single host, graph is working fine.
But I select several hosts, I get the following error in Grafana :
 Error message: Bad Request These fields have problems: host_name
 
In https://forum.checkmk.com/t/use-of-template-variables/46171, they adviced to open an issue here.

**Comment by BenediktSeidl** [comment]
Thanks for opening this issue. I'm sorry to inform you, that in the time between I've suggested opening this GitHub issue on the forum, someone created #247 so I have to close this one as a duplicate.  Please leave your :+1: on the other issue, so we can see that this issue is important for multiple people. Thanks!
