### ISSUE TITLE
Support for Variables

### ISSUE THREAD

**Issue by Brazier85** [Checkmk/grafana-checkmk-datasource#28]
It would be nice if you can use variables in the provided fields eg. host. So it is possible to create dynamic dashboards with rows.

![image](https://user-images.githubusercontent.com/1213924/70042647-886cf400-15bf-11ea-916d-76b053e46209.png)

**Comment by amandahla** [comment]
+1

**Comment by cstegm** [comment]
+1

**Comment by doctore74** [comment]
+1

**Comment by mpeuser** [comment]
+1

**Comment by ruohki** [comment]
This feature is very much needed. Iam trying to aggregate data from multiple sources for a single host that id like be able to select from a list. I dont want to copy & pastet he same dashboard for each of the machines... Imagine if you change something and have to rework 100+ dashboards

**Comment by amandahla** [comment]
Happy to have your thoughts/help on this PR https://github.com/tribe29/grafana-checkmk-datasource/pull/38

:-)

**Comment by rs-ubaldi** [comment]
Really appreciate your PR, unfortunately several months old and still not merged

**Comment by jeroenvermeulen** [comment]
@cbmueller Please take a look at the PR, we need this feature.

**Comment by LarsMichelsen** [comment]
Thanks for taking the time to participate. cbmueller is not working on the connector anymore.

In the background we are currently preparing the connector for the new Grafana API. It's more like a complete rewrite which has to be done because of changed APIs from the Grafana side. Once this is done and the existing features are working,  we'll check out the feature requests and PRs.

We understand the need for this feature and will discuss it's priority internally.

**Comment by viramamur** [comment]
Please confirm if this feature is available now on the new plugins.

**Comment by godspeed-you** [comment]
Hi again,

as @LarsMichelsen also mentioned: We are aware, that this is a fundamental missing feature in the plugin. And even though, we currently do not know, when we will have the time to continue adding new features to this project, this one will be next. 

Also, as we did most recently a complete rewrite of the plugin, we will add it to the new version instead of to the old one. This is important, especially regarding possible PRs.
As mentioned in other enhancement issues: We will come back to you, hopefully with good news and something to test. But please be patient with us as it may take some time.

Best Regards,
Marcel

**Comment by sowdenraymond** [comment]
Hi Marcel,

Any news on the variable support yet?

**Comment by BenediktSeidl** [comment]
We are currently in requirements research for this feature. You can help us by answering the following question: How do you want to use variables with this data source? Please describe your use case as detailed as possible, so we can understand what you want to accomplish.

Example:
* Purpose: Quick overview of the most important metrics of a single host
* Variables:
    * "Host" is a list of all hosts
* Dashboard:
    * Panel "Memory"
        * Filter Hostname: $Host
        * Filter Service: "Memory"
        * Template: "Active and Inactive Memory"
    * Panel "CPU"
        * Filter Hostname: $Host
        * Filter Service: "CPU utilization"
        * Template: "CPU utilization"
     * Panel "Disks"
        * _similar to above_
     * Panel "Network"
         * _similar to above_

**Comment by sowdenraymond** [comment]
Hi Benedikt,

On the Panel screen after selecting the CheckMK datasource, hostname is currently a drop down list, to select a list of hosts configured in CheckMK. We should be able to enter a variable here like $dbserver, then configure a variable on the dashboard that points $dbserver to the hostname, so that it resolves.

In our case we have hundreds of panels, so if we configure a new dashboard, or change a hostname, we need to go and touch every single panel and select the correct host name from the list, whereas previously we could just change the dashboard variables, and not have to touch any of the panels.

Hope this helps, let me know if you want more info.

Regards

Raymond

**Comment by paubartoli** [comment]
Hi @BenediktSeidl ,
As most of the people has pointed out, there will be great if we were able to use grafana variables onto the hostame or hostnameRegex fields on the checkMK plugin. 

Here's the link to the official grafana plugin development documentation section that references how to implement this feature:

>  [](https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/)

Hope it helps.

Pau

**Comment by sowdenraymond** [comment]
Hi @BenediktSeidl,

Any update on this?

We are currently grandfathered in on our version of CheckMK, and we cannot upgrade until we get this functionality, so it is a bit of a security worry..

Regards

Raymond

**Comment by BenediktSeidl** [comment]
it's definitely the next feature on our roadmap. i want to release the next beta of version 3.0.0 of the plugin this week, after that we will work on the variable support.

**Comment by BenediktSeidl** [comment]
If you want to test the pre-alpha version of the plugin with variable support, you can so [tribe-29-checkmk-datasource-3.0.1-alpha.1.testbuild.5079989444](https://github.com/Checkmk/grafana-checkmk-datasource/suites/13145182930/artifacts/714631400) (the plugin is zipped twice, sorry)
Please report any bugs or problems regarding the variables in this issue.
Currently supported variable types are site, host and service. If you need other variables, please report here and describe your use case.

**Comment by sowdenraymond** [comment]
Hi Benedikt,

Thanks, I have loaded the pre-alpha version.

Some comments: I selected CheckMK < 2.2 for the version of CheckMK, and the Raw Edition as we are running CheckMK  2.0.0p9, this tested fine!

Then when adding a panel, the Site dropdwon does not work, it does not list the current site, and i cannot type in this filed, it just says "Invalid ident: sites"

The hostname picks up the dashboard variables now, thank you!

Then I select the service, and single metric for the graph type, but the drop down for single metric, does not return only the counters for the single metric I selected, it seems to return all the counters available.

LEt me know if you need any screenshots or similar.

**Comment by sowdenraymond** [comment]
Hi Benedikt,

I updated CheckMK to 2.2.0 and Grafana to 9.5.2, and everything works on the latest versions.

This is awesome!

Thank you :)

**Comment by BenediktSeidl** [comment]
Nice to hear! I created a new internal note for changing the version dropdown to make it clear that 2.1.0 is not fully supported.

**Comment by jsandner** [comment]
Great work.
I'm using checkmk 2.1p28 and grafana 9.5.2
Everything seems to work
- fill variables  using checkmk queries, with graphical filter definition (awsome)
- use variables in visualizations
This is quite exactly what I needed.

Thank you!

**Comment by BenediktSeidl** [comment]
I just released 3.1.0-beta.1 which is the first (pre-)release with variable support: https://github.com/Checkmk/grafana-checkmk-datasource/releases/

**Comment by godspeed-you** [comment]
As you may have noticed already, the support for variables is now fully implemented and released. We know this has been a long wanted and urgently needed feature and so, we want to thank all of you who participated during this process and for your patience. The input, not only in this particular issue, but on other platforms as well, has been of much value and gave us the ability to add actual value to the plugin.

**Comment by dnlldl** [comment]
So, how does this work exactly? I updated to the latest plugin version, could variables allow me to monitor uptimes of multiple hosts in a single dashboard without having to specify every host individually but with a regex instead?

**Comment by BenediktSeidl** [comment]
please use the [forum](https://forum.checkmk.com/) and tag it with [grafana](https://forum.checkmk.com/tag/grafana) for general help questions regarding checkmk and grafana.
