### ISSUE TITLE
Plugin for Grafana Cloud in the official community catalog

### ISSUE THREAD

**Issue by 7oku** [Checkmk/grafana-checkmk-datasource#47]
Hi, 

we're using Grafana Cloud as service and want to configure our check_mk as data source. 

Grafana Cloud installs plugins through the public catalog rather than installing from a .zip or GitHub clone, so I currently do not see any way to have them work together.

Would it be possible for you to make the plugin available in the Grafana catalog? According to them, everyone in the community can offer their plugin through https://github.com/grafana/grafana-plugin-repository.

Thanks!

**Comment by godspeed-you** [comment]
Hi @7oku,
it's been a while, since open this request and discussed that internally during the last weeks and months. Even if we have no final decision, I wanted to share some insights with you. 

We would also prefer having the plugin integrated into the official Grafana catalog. Unfortunately, this is not as easy for us as a company, as it would be for a private person. I guess, it's no secret, that this project is completely free for all users, regardless if they use our free or a license based Checkmk edition. The consequence is, that we do not profit from this project in any way, beside the fact that we get positive feedback of happy users. 
On the other side, to bring our plugin into the Grafana catalog is associated with a notable amount of yearly costs as the maintenance is done by tribe29 as a company. It would be free, if the maintenance would be a private person. 

Although we did not decide yet, if we want to lift the investment: These are the reasons for our hesitates. I will update this issue, if we made a final decision.

I hope, this helps you and others following this issue and gives you the insights, I promised you.

Best Regards,
Marcel

**Comment by godspeed-you** [comment]
Hi again @7oku,
it's been a long time and we've been working on that case also since a long time. We finally came to an agreement with Grafana and the plugin is now listed in the Grafana catalog: https://grafana.com/grafana/plugins/checkmk-cloud-datasource/ 

As you will see the limitations anyway, an explanation here already: The signed plugin in the catalog is limited to the Checkmk cloud edition. This is part of the result of the agreement between Grafana and Checkmk. The unsigned plugin will be continue to be available and will not differ features wise. We're basically building the plugin two times and they only differ in the signing. This allows us to provide the full feature set to all our users and be break even at the same time. 

Best Regards,
Marcel
